@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class AddressBook
Class ModelManager
Class UserPrefs

Class UniquePersonList
Class Person
Class Address
Class Email
Class Name
Class Phone
Class Tag
Class UniqueTagList
Class UniqueTeamList
Class UniquePositionList
Class Injury
Class Team
Class Position
}

AddressBook .up.|> ReadOnlyAddressBook

ModelManager ..|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -down-> AddressBook
ModelManager -up->   UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *-right-> UniquePersonList
AddressBook *-down-> UniqueTagList
AddressBook *-left-> UniqueTeamList
AddressBook *-up-> UniquePositionList

UniquePersonList -right-> Person
UniqueTagList -down-> Tag
UniqueTeamList -left-> Team
UniquePositionList -up-> Position


Person -down-> Name
Person -right-> Phone
Person -up->   Email
Person -left-> Address
Person -down->  Team
Person -right-> Position
Person -up->    Injury


note right of Person
  isCaptain: boolean
end note

ModelManager -right-> Person
@enduml
