@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class AddressBook
Class ModelManager
Class UserPrefs

Class UniquePersonList
Class UniqueTeamList
Class UniquePositionList
Class Person
Class Team
Class Position
}

AddressBook .up.|> ReadOnlyAddressBook
ModelManager ..|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
UserPrefs .up.|> ReadOnlyUserPrefs

ModelManager --> AddressBook
ModelManager --> UserPrefs

AddressBook --> UniquePersonList
AddressBook --> UniqueTeamList
AddressBook --> UniquePositionList

UniquePersonList --> "*" Person
UniqueTeamList --> "*" Team
UniquePositionList --> "*" Position

Person --> "0..1" Team
Person --> "0..1" Position
@enduml
